#define CPU_CLIPS_NEGATIVE 0
#define CPU_CLIPS_POSITIVE 0
#define HAVE_CALLOC 1
#define HAVE_CEIL 1
#define HAVE_DLFCN_H 1
#define HAVE_FFTW3 1
#define HAVE_FLOOR 1
#define HAVE_FMOD 1
#define HAVE_FREE 1
#define HAVE_INTTYPES_H 1
#define HAVE_LIBM 1
#define HAVE_LRINT 1
#define HAVE_LRINTF 1
#define HAVE_MALLOC 1
#define HAVE_MEMCPY 1
#define HAVE_MEMMOVE 1
#define HAVE_MEMORY_H 1
#define HAVE_SIGALRM 1
#define HAVE_SIGNAL 1
#define HAVE_SNDFILE 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_UNISTD_H 1
#define PACKAGE "libsamplerate"
#define PACKAGE_BUGREPORT "erikd@mega-nerd.com"
#define PACKAGE_NAME "libsamplerate"
#define PACKAGE_STRING "libsamplerate 0.1.9"
#define PACKAGE_URL "http://www.mega-nerd.com/libsamplerate/"
#define PACKAGE_VERSION "0.1.9"
#define STDC_HEADERS 1
#define VERSION "0.1.9"
