/*/////////////////////////////////////////////////////////////////////////////
//
//     spiral_private.h
//
//     This library was generated by Spiral 6.0, developed at Carnegie Mellon
//     University, http://www.spiral.net. This code is distributed under the
//     GNU general purpose software license version 2.0.
//
//     Commercial licenses and support are available through SpiralGen, Inc.
//     fft@spiralgen.com
//
*/

#ifndef __SPIRAL_PRIVATE_H__
#define __SPIRAL_PRIVATE_H__

#ifdef __cplusplus
extern "C" {
#endif

extern  float D267[128];
       
extern  float D268[256];
       
extern  float D269[512];
       
extern  float D270[1024];
       
extern  float D271[2048];
       
extern  float D272[4096];
       
extern  float D273[8192];
       
extern  float D274[16384];
       
extern  float D275[128];
       
extern  float D276[256];
       
extern  float D277[512];
       
extern  float D278[1024];
       
extern  float D279[2048];
       
extern  float D280[4096];
       
extern  float D281[8192];
       
extern  float D282[16384];
       
extern  double D283[128];
       
extern  double D284[256];
       
extern  double D285[512];
       
extern  double D286[1024];
       
extern  double D287[2048];
       
extern  double D288[4096];
       
extern  double D289[8192];
       
extern  double D290[16384];
       
extern  double D291[128];
       
extern  double D292[256];
       
extern  double D293[512];
       
extern  double D294[1024];
       
extern  double D295[2048];
       
extern  double D296[4096];
       
extern  double D297[8192];
       
extern  double D298[16384];
       

#ifdef __cplusplus
}
#endif

#endif /* __SPIRAL_PRIVATE_H__ */
